In [12]:
import numpy as np

# Input adjacency matrix
n = int(input("Enter number of vertices: "))
adj_matrix = np.zeros((n, n))

for i in range(n):
	adj_matrix[i] = list(map(int, input(f"Enter adjacency list for vertex {i}: ").split()))
print('Adjacency Matrix:', adj_matrix)
# Transpose of the adjacency matrix for authority calculation
adj_matrix_T = np.transpose(adj_matrix)

def normalize(vector):
	# Normalize the vector by dividing by total number of 1s in adjacency matrix
	norm = sum(vector)
	return vector / norm if norm != 0 else vector

# Initialize authority and hub scores
authority = np.ones(n)
hub = np.ones(n)
print('Initial Authority Scores:', authority)
print('Initial Hub Scores:', hub)
# Convergence threshold
epsilon = 1e-6
delta = 1
iteration = 10

while delta > epsilon:
	# Update authority score
	old_authority = authority
	old_hub = hub
	authority = [sum(hub[j] for j in range(n) if adj_matrix_T[i][j] == 1) for i in range(n)]
	authority = normalize(authority)
	# Update hub score
	hub = [sum(authority[j] for j in range(n) if adj_matrix[i][j] == 1) for i in range(n)]
	hub = normalize(hub)
	delta =	max(max(abs(authority - old_authority)), max(abs(hub - old_hub)))
	# Normalize authority scores
	iteration += 1
	print(f"Iteration {iteration}")
	print("Authority Scores:", authority)
	print("Hub Scores:", hub)
print(f"Converged in {iteration} iterations")
print("Final Authority Scores:", authority)
print("Final Hub Scores:", hub)

Adjacency Matrix: [[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 1. 1.]]
Initial Authority Scores: [1. 1. 1. 1.]
Initial Hub Scores: [1. 1. 1. 1.]
Iteration 11
Authority Scores: [0.375 0.25  0.25  0.125]
Hub Scores: [0.11111111 0.16666667 0.27777778 0.44444444]
Iteration 12
Authority Scores: [0.34042553 0.27659574 0.21276596 0.17021277]
Hub Scores: [0.09803922 0.15686275 0.28431373 0.46078431]
Iteration 13
Authority Scores: [0.33823529 0.27941176 0.20955882 0.17279412]
Hub Scores: [0.09677419 0.15619694 0.2852292  0.46179966]
Iteration 14
Authority Scores: [0.33820725 0.27972028 0.20915448 0.17291799]
Hub Scores: [0.09659425 0.15619495 0.28537874 0.46183206]
Iteration 15
Authority Scores: [0.33824338 0.27976256 0.20907992 0.17291415]
Hub Scores: [0.09655803 0.15620875 0.28540969 0.46182354]
Iteration 16
Authority Scores: [0.33825626 0.27977039 0.20906274 0.17291061]
Hub Scores: [0.09654936 0.15621352 0.28541709 0.46182003]
Iteration 17
Authority Scores: [0.3382599  0.27977218 0.2